# Generated by Django 2.1.3 on 2018-11-20 06:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 20, 6, 1, 14, 668281)),
        ),
    ]
